name: Test Auto-sklearn Import

on: [push, pull_request]

env:
  model: "Auto-sklearn"
  min_python_version: 3.6
  max_python_version: 3.12

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      python_versions: ${{ steps.set-matrix.outputs.python_versions }}
    steps:
      - name: Generate Python version list dynamically
        id: set-matrix
        run: |
          VERSIONS=$(seq ${{ env.min_python_version }} 0.1 ${{ env.max_python_version }} | jq -R -s -c 'split("\n")[:-1]')
          echo "python_versions=$VERSIONS" >> $GITHUB_OUTPUT

  test-python-versions:
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix:
        python_version: ${{ fromJson(needs.generate-matrix.outputs.python_versions) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Run `check_import.yml` workflow
        uses: reproduce-matbench/.github/workflows/check_import.yml@main  
        with:
          model: ${{ env.model }}
          python_version: ${{ matrix.python_version }}
          system_dependencies: git
          conda_env_file: benchmarks/matbench_v0.1_${{ env.model }}/environment.yml

        continue-on-error: true  # Allows errors but continues execution

      - name: Save failure message if it fails
        if: failure()
        run: |
          echo "Python ${{ matrix.python_version }} failed!" >> summary.log

      - name: Upload failure summary
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: summary-log
          path: summary.log

  summarize-results:
    runs-on: ubuntu-latest
    needs: test-python-versions  # Runs only after all jobs complete
    steps:
      - name: Download all failure logs
        uses: actions/download-artifact@v4
        with:
          name: summary-log

      - name: Print summary
        run: |
          echo "Python Version Test Summary:"
          cat summary.log || echo "All tests passed!"
