name: Test Auto-sklearn Import

on: [push, pull_request]

env:
  model: "Auto-sklearn"
  min_python_version: 3.6
  max_python_version: 3.12

jobs:
  test-python-versions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Allows all versions to run even if one fails
      matrix:
        python_version: [3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 3.12]  # List of versions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Run `check_import.yml` workflow
        uses: ./.github/workflows/check_import.yml  # Calls reusable workflow
        with:
          model: ${{ env.model }}
          python_version: ${{ matrix.python_version }}
          system_dependencies: git
          conda_env_file: benchmarks/matbench_v0.1_${{ env.model }}/environment.yml
          # pip_requirements_file: benchmarks/matbench_v0.1_${{ env.model }}/requirements.txt

        continue-on-error: true  # Allows errors but continues execution

      - name: Save failure message if it fails
        if: failure()
        run: echo "Python ${{ matrix.python_version }} failed!" >> summary.log

  summarize-results:
    runs-on: ubuntu-latest
    needs: test-python-versions  # Runs only after all jobs complete
    steps:
      - name: Print summary
        run: |
          echo "Python Version Test Summary:"
          cat summary.log || echo "All tests passed!"
